### ISSUE TITLE
NameError: name 'pillow' is not defined

### ISSUE THREAD

**Issue by sicenul** [sereaf/asciipy#1]
Hi, I'm interested in testing asciipy, but end up with error.
```
$ pip install asciipy
Requirement already satisfied: asciipy in ./env/lib/python3.7/site-packages (0.0.5)
Requirement already satisfied: opencv-python in ./env/lib/python3.7/site-packages (from asciipy) (4.4.0.46)
Requirement already satisfied: Pillow in ./env/lib/python3.7/site-packages (from asciipy) (6.1.0)
Requirement already satisfied: numpy in ./env/lib/python3.7/site-packages (from asciipy) (1.17.2)

$ python tes.py 
Traceback (most recent call last):
  File "tes.py", line 6, in <module>
    image.ascii_terminal() # print an ascii image to the terminal
  File "/home/youza/python/tes/env/lib/python3.7/site-packages/asciipy/image.py", line 148, in ascii_terminal
    if pillow and (len(img.getbands()) > 3):
NameError: name 'pillow' is not defined
```

Here it is the tes.py:
```
from asciipy import AsciiVideo, AsciiImage

# image
img_path = 'qrcode.png'
image = AsciiImage(img_path)
image.ascii_terminal() # print an ascii image to the terminal
```

**Comment by sereaf** [comment]
Hi, thanks. I think i've found the issue. I'm updating shorly.

**Comment by sereaf** [comment]
Hey, so I updated it on pypi.org so you can update with pip. I tested it and it should work now. Have fun!
